### ISSUE TITLE
A MalformedMessage escaping during sync

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1001]
on master

### What is wrong?

```
   ERROR  08-28 16:13:14            Connection  Unexpected error in <p2p.connection.Connection object at 0x7f3a00b1f198>, exiting
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/p2p/transport.py", line 241, in recv
    header = self._decrypt_header(header_data)
  File "/home/jcarver/code/trinity/p2p/transport.py", line 322, in _decrypt_header
    f'Invalid header mac: expected {expected_header_mac}, got {header_mac}'
p2p.exceptions.DecryptionError: Invalid header mac: expected b'\xbe\xe5\x7fmM\xe9\xc6\x05\xbc\xb2\x93P:2b\xdf', got b"\xa1\xd1o\x06'`\xfd\x8f\xcd~<\xb82\x96\xa8\x95"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 322, in _do_multiplexing
    async for protocol, cmd, msg in msg_stream:
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 66, in wait_iter
    timeout=timeout,
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 153, in cancellable_wait
    return done.pop().result()
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 58, in stream_transport_messages
    raw_msg = await transport.recv(token)
  File "/home/jcarver/code/trinity/p2p/transport.py", line 247, in recv
    raise MalformedMessage from err
```

### How can it be fixed

Related to #901 ?

cc @pipermerriam

**Comment by pipermerriam** [comment]
Looks like this is easily catchable by wrapping the `with multiplexer.multiplex()` call in `Connection._run()` in a `try/except`.

**Comment by pipermerriam** [comment]
However, I'm getting this `MalformedMessage` error when connecting to my own local node which suggests that there is actually something wrong with how we are reading the peer message....

**Comment by pipermerriam** [comment]
One theory is that we're doing some sort of *partial* read of a message during the handshake but it gets interrupted, and then when the multiplexer picks back up in the `Connection` object it *thinks* it is reading from the beginning of a message but it's actually reading from the middle of the stream...

**Comment by pipermerriam** [comment]
More likely due to https://github.com/ethereum/trinity/pull/962

**Comment by gsalgado** [comment]
I've recently started seeing DecryptionErrors causing MalformedMessages again (easily reproducible by running `scripts/peer.py` against a local geth instance). After much digging around I realized that's because the `recv()` is being cancelled during the header read, which was thought to be fine but turns out not to be the case as the cancelled `_reader.readexactly()` (https://github.com/ethereum/trinity/blob/dfc47bc94feaf9c5c1044c6003ac4a898e034886/p2p/transport.py#L246-L251) call may consume data from the buffer, so when we reset the transport's state (https://github.com/ethereum/trinity/blob/dfc47bc94feaf9c5c1044c6003ac4a898e034886/p2p/transport.py#L272-L277) to IDLE and later resume multiplexing (after the handshake), we will be reading either part of the msg header or the msg body, and thus the decryption will fail

I've confirmed this by adding some debug logging to `read()` above, and this is what I see:

```
11:51:35 INFO: Before readexactly(), buffer: bytearray(b'\x88\xb3\xc6%8`\x00`\xebL>\xa2\xb7=\x8d\xf3\xb6H.\'\xc8\x82\x960,\xef\xd6\x13$\x80\xa2l%\x84\xae\xa5A\x93"\xf4\x97\xf7$\x1bYRS_\xed\xd2\xb5\xbd\xac\xbaD\xb0\xb5^\xd4 \x1a\xbe\x99\x8e')
11:51:35 INFO: After readexactly() cancelled, buffer: bytearray(b'%\x84\xae\xa5A\x93"\xf4\x97\xf7$\x1bYRS_\xed\xd2\xb5\xbd\xac\xbaD\xb0\xb5^\xd4 \x1a\xbe\x99\x8e')
11:51:35 INFO: Transport cancelled during header read. resetting to IDLE state
11:51:35 INFO: Before readexactly(), buffer: bytearray(b'%\x84\xae\xa5A\x93"\xf4\x97\xf7$\x1bYRS_\xed\xd2\xb5\xbd\xac\xbaD\xb0\xb5^\xd4 \x1a\xbe\x99\x8e')
11:51:35 INFO: Bad message header from peer <p2p.transport.Transport object at 0x7f458afbde10>: Error: DecryptionError('Invalid header mac: expected d4a45786bb62e4a6eac250d1e93add10, got edd2b5bdacba44b0b55ed4201abe998e')

```

**Comment by gsalgado** [comment]
One way to fix this would be to change https://github.com/ethereum/trinity/blob/dfc47bc94feaf9c5c1044c6003ac4a898e034886/p2p/multiplexer.py#L331-L341 to wait for 1s as well if the state is HEADER, but tbh I am not comfortable with the current approach as it means any time we do not receive a msg from a remote in less than 1s after the handshake is complete, we flag the transport as corrupt. And if we increase that timeout we would be adding a significant delay when terminating a running  `Peer`

**Comment by gsalgado** [comment]
@pipermerriam any opinions/suggestions?

**Comment by pipermerriam** [comment]
I don't have anything to suggest that's a ready to implement solution but my gut says to look in the following direction:

We currently use an async iterator as the mechanism for reading the messages off the transport.  I think this causes some problems because it isn't trivial to *pause* and resume async iterators without cancelling the underlying coroutine.  I would look using something like an `asyncio.Queue` in place of the async iterator.  This would allow us to use `asyncio.ensure_future` to start a long running background task.  This would remove the need for us to stop and restart the message stream between handshake and creation of the `Connection`.  We'd need to pass around the `asyncio.Task` object to be sure that it gets properly handled and cleaned up, but that shouldn't be too difficult.

I hope that helps.

**Comment by gsalgado** [comment]
@pipermerriam I ended up extending the `Multiplexer` with APIs for starting/stopping the background task instead of passing an `asyncio.Task` around, but in principle I think #1750 is what you suggested above

**Comment by pipermerriam** [comment]
@gsalgado looked it over today and :+1: on approach.  I wasn't set on the task passing as much as the migration away from start/stopping the async generator (and the underlying transport corruption stuff that was necessary to deal with that.)
