### ISSUE TITLE
Node Discovery often drops pings

### ISSUE THREAD

**Issue by lithp** [ethereum/trinity#118]
* py-evm Version: c4e38746

### What is wrong?

My log file is full of triplets like this:

```
   DEBUG  01-07 11:38:42     DiscoveryProtocol  unexpected v4 pong from <Node(0x6a2c@209.97.174.78)> (token == 0x3e72df0d5fd08ea0a476ca1047aa8db586ae58a94bf8cee060dc312b17ffc0b8)
   DEBUG  01-07 11:38:49     DiscoveryProtocol  timed out waiting for pong from <Node(0x6cd0@209.97.174.78)> (token == 0x3e72df0d5fd08ea0a476ca1047aa8db586ae58a94bf8cee060dc312b17ffc0b8)
   DEBUG  01-07 11:38:49     DiscoveryProtocol  bonding failed, didn't receive v4 pong from <Node(0x6cd0@209.97.174.78)>
```

In fact, I've dug into all instances of "unexpected v4 pong from" and nearly all of them are part of a triple of messages like the above one. We receive a pong from the node (with the wrong public key), throw it away, and then time out the node. For each node that this happens with we seem to repeat the process about every 9 minutes.

- Maybe this is the fault of the nodes we're talking with, and this log spam could be reduced by remembering which nodes we've previously rejected and not talking to them for a while?
- Maybe we're... incorrectly parsing the public key? This seems unlikely but it's possible.
- Maybe these nodes aren't meant to be part of the network, they're just here to monitor the network, and they intentionally continually change their public keys?

**Comment by lithp** [comment]
Potentially a duplicate of #88

**Comment by pipermerriam** [comment]
> Maybe we're... incorrectly parsing the public key?

Worth a cursory glance at least.

> this log spam could be reduced by remembering which nodes we've previously rejected and not talking to them for a while?

Related to https://github.com/ethereum/trinity/issues/33 in some way.  Even a rudimentary (and maybe ephemeral) blacklist mechanism would be useful to have on hand.

**Comment by veox** [comment]
Perhaps this is same as PR https://github.com/ethereum/py-evm/pull/1011 (or similar)?..

(Also, about half the nodes received through v4 discovery are not ETH main-net nodes.)

**Comment by veox** [comment]
> * Maybe these nodes aren't meant to be part of the network, they're just here to monitor the network, and they intentionally continually change their public keys?

Quite possible. [Look up](https://www.ethernodes.org/network/1/nodes), for example:

```
104.207.156.26
159.203.13.0
104.248.208.105
178.128.233.97
...
```

The list goes on. Therefore my approach above.

**Comment by lithp** [comment]
ethernodes.org is super useful, thanks for the tip. `209.97.174.78`, for example, really does seem to change it's public key all the time. I wonder why.

**Comment by veox** [comment]
A few things come to mind:

* it's a monitoring service, just like `ethernodes` (or the research paper linked earlier);
* it's a CI machine.

**Comment by lithp** [comment]
Just skipped through the paper, these are indeed some very pretty charts!

[After reading about peer discovery](https://github.com/ethereum/devp2p/blob/master/discv4.md) it sounds like a plausible mechanism is:
- This node adds itself to the DHT (I'm still not sure exactly how this happens)
- Some time passes and the node is restarted, with a different node id
- Our node is told about the old public key and sends a ping
- The protocol has no indication of who the packet was intended for, so the new instance replies with a pong.
- We reject the pong because we're (presumably) talking with a different node.

If these nodes are a minority then maybe ignoring them makes sense. Is there any harm to accepting the pong and changing our idea of what the node's public key should be? This might let us salvage the relationship.

**Comment by veox** [comment]
> Is there any harm to accepting the pong and changing our idea of what the node's public key should be?

I'd assume yes, there's harm. There's no sense in doing this ping/pong if the ping is opportunistically discarded.

Consider the remote is a bootnode, or a static node - where eID mismatch is indication of things going wrong, e.g. a MITM attack (by some stretch of imagination); or - as it says on the tin - an indication by the counter-party that the set-up has changed.

Accepting a mismatched eID in the two cases above is certainly not what a node operator would expect. So, it would require special-casing... :/

> This might let us salvage the relationship.

I'd argue this is a relationship not worth salvaging. :)

The DHT is full of garbage. Neighbours are optimistically passing this garbage around. Some retain all the garbage they can as long as they can, due to their operators' preference.

(I've recently looked up a node eID/IP reported on a "network monitoring" service (not etherchain's), out of curiosity. It was present. I've turned the node "off" ~6 months ago. The service is reporting on stale gossip.)

The "proper" approach is reducing the score of stale entries drastically, and (perhaps) reducing the score of neighbours passing these around a little.

-----

OT: I'm starting to wonder whether GDPR applies to P2P network monitoring.

**Comment by gsalgado** [comment]
ISTM there's nothing we can do about this, so I'll just add a comment to where we log the unexpected pong (so that the next person who notices them will know it's nothing to worry about) and close this. Feel free to reopen if you think we should do something else
