### ISSUE TITLE
Quickly discover sparse peers with particular subprotocol

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1299]
### What is wrong?

In order for Beam Sync to really fly, we want to pass around witness metadata. We will add a custom subprotocol (see #1225 ), but in the short-medium term, the number of nodes that support this new subprotocol (relative to total nodes in the network) will be low.

Currently, groping around the network for a particular subprotocol is very slow, when the number of supporting nodes is sparse (since it's a guess-connect-and-check mechanism).

### How can it be fixed

Use some of the updated discovery V4 (backported from V5?) mechanisms to check supported subprotocols in ENRs during discovery, before connecting.

**Comment by gsalgado** [comment]
I believe using the discv4 **random node lookup**, even with ENR support, will not actually allow us to discover nodes that support a minority sub-protocol in a timely fashion. That's because the lookups are always random and even though ENR would allow us to not connect unnecessarily, we'd still have to be lucky for a lookup to hit a node that supports the sub-protocol. That was my experience when testing with LES node discovery.

I think what we need is discv5's lookup by topic ([TOPICQUERY](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#topicquery-request-0x08)) mechanism.

**Comment by pipermerriam** [comment]
@gsalgado one idea was to keep a local persistent database of historically seen ENR records that we could then query on startup to *try* and see if the node is still around and online...

**Comment by carver** [comment]
> @gsalgado one idea was to keep a local persistent database of historically seen ENR records that we could then query on startup to _try_ and see if the node is still around and online...

Do you mean something that we ship with trinity?

**Comment by pipermerriam** [comment]
Yes, some internal component that both tracks seen ENR records and maybe also crawls the network periodically to keep the database populated with fresh records.

**Comment by gsalgado** [comment]
I'm running some experiments with our ENR-enabled discv4 implementation and this is what I've found so far:

 * 1/4th of all nodes that reply to our pings support the v4 ENR extension
 * The vast majority of those include a forkid in their ENRs

That means we should be able to populate a large DB of ENRs somewhat quickly and if we persist it we could, on startup, lookup peers that previously had compatible forkids (possibly re-fetching their ENRs to ensure that's still the case) and immediately start syncing. For minority sub-protocols we'd still need to experiment some more to see how often we'd come across them, but as soon as we do so we'll know (because of the forkid) and we can immediately connect to them (currently that can never happen as we connect to nodes randomly)

**Comment by gsalgado** [comment]
In my comment above there's one important thing missing, which is that we need to identify peers that support a given sub-protocol and not just which fork they're on. For that we're going to have to make sure peers supporting that sub-protocol include their list of supported protocols in their ENRs -- which currently very few seem to do

**Comment by gsalgado** [comment]
https://github.com/ethereum/go-ethereum/pull/19800 is why there are very few nodes that include their capabilities in their ENRs. I'm waiting to hear from geth devs what the new model looks like

**Comment by pipermerriam** [comment]
Fast and dirty plan could be...

1. setup long running trinity nodes in VPS environment with priority peer slots to a dedicated geth node that we control.
2. put these trinity nodes in our list of bootstrap nodes.
3. add some custom peer management logic to these nodes to prioritize `trinity <-> trinity` connections.

second part of the plan.

4. Add an indicator in the ENR record that a client publishes access lists (aka supports new custom subprotocol)
5. Adjust our discovery code to perform periodic full crawls of the discovery network, storing ENR records in a query-able format
6. Use ENR record DB to find and prioritize peer candidates which support the custom subprotocol for access lists.

I believe everything in this list is pure engineering work and would give us a viable way to bootstrap our nodes onto the network in such a manner that they'd have a semi-reliable feed of access lists which **in theory** lets them "keep up" via cooperation and swarming behavior.
