### ISSUE TITLE
wheel-cli/long-run-integration tests fail intermittently

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1435]
https://circleci.com/api/v1.1/project/github/ethereum/trinity/168014/output/108/0?file=true&allocation-id=5e04f8648b44031be926bab5-0-build%2F290499C8

Not clear to me which tests are failing, but there are a few tracebacks for an EOFError in the logs for the test above at https://circleci.com/api/v1.1/project/github/ethereum/trinity/168014/output/108/0?file=true&allocation-id=5e04f8648b44031be926bab5-0-build%2F290499C8

**Comment by cburgdorf** [comment]
```
Traceback (most recent call last):\n'
  File "<string>", line 1, in <module>\n'
  File "/usr/local/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main\n'
    exitcode = _main(fd)\n'
  File "/usr/local/lib/python3.7/multiprocessing/spawn.py", line 113, in _main\n'
    preparation_data = reduction.pickle.load(from_parent)\n'
EOFError: Ran out of input\n'
```

**Comment by cburgdorf** [comment]
This seems to be the most frequent cause of error currently. It seems pretty recent so I suspect it has something to do with our recent change in how we spawn processes. /cc @pipermerriam

**Comment by gsalgado** [comment]
I've had a look at this again and it seems like the error can happen on any of the trinity-cli tests. And some of those tests don't even fail when that error happens (e.g https://circleci.com/api/v1.1/project/github/ethereum/trinity/176696/output/108/0?file=true&allocation-id=5e1f2c6db9b49522ebe888d1-0-build%2F67431DD8 was a successful run but `test_expected_logs_for_full_mode` did raise that EOFError)

I haven't managed to reproduce it locally, so am giving up for now. Has anybody managed to reproduce it locally?

**Comment by cburgdorf** [comment]
The only tests that would fail are those that actively scan for errors via `run_command_and_detect_errors` or `scan_for_errors` directly. 

>was a successful run but test_expected_logs_for_full_mode did raise that EOFError)

Right, that test does only care if the right logs are written but doesn't care about any unrelated logs/errors coming up.

>I haven't managed to reproduce it locally, so am giving up for now.

I tried to reproduce it and I also tried to google the hell out of it. I would bet it is something inside the `asyncio_run_in_process` library that recently took over the launch of the processes.

One thing that's interesting, I *think* I've only seen this error coming up on Python 3.7 not 3.6. If that is the case, then we might get away with disabling the affected tests on Python 3.7 for now based on the assumption that we are still half covered through the Python 3.6 based tests.

I don't feel good disabling these tests because they have saved our asses so often when none of our other tests would detect serious issues but maybe if we would still be covered through Python 3.6 that would still be ok.

**Comment by gsalgado** [comment]
The jobs linked in the description here are actually [py36-wheel-cli](https://circleci.com/api/v1.1/project/github/ethereum/trinity/168014/output/108/0?file=true&allocation-id=5e04f8648b44031be926bab5-0-build%2F290499C8)

**Comment by carver** [comment]
I just ran into this again

**Comment by carver** [comment]
> Ah damn..I mean, another thing we can do is, to at least temporally explicitly whitelist this specific error to be allowed and add an issue to tackle it at some later point in time.

Hm, it's not obvious how to do this, because the trigger line is the start of the Traceback, which isn't very unique. Seems like we'll have to actually fix it. @pipermerriam does this pickle-related error (there's a copy back up in this thread) look familiar / related to the asyncio-run-in-process library?

**Comment by cburgdorf** [comment]
>Hm, it's not obvious how to do this, because the trigger line is the start of the Traceback, which isn't very unique

Yeah, that's true. We would have to make the triggering smarter to achieve this. Probably better to invest that time into the actual fix :)

**Comment by pipermerriam** [comment]
The pickle error above should not be related to `async-run-in-process` since that library doesn't use `multiprocessing` at all.  I believe the only place we are still using `multiprocessing` is to run the database process which would be trivial-ish to convert over to a component, though it will require us implementing a concept of a DAG for the components so that they startup and shutdown in the proper order.

**Comment by cburgdorf** [comment]
I guess we could use the `test_does_not_throw_errors_on_short_run` test to find the causing change via git bisect. Just need to find the number of runs that reliably can reproduce at least a single failure. I might do that.

Also, isn't logging still using `multiprocessing` because I think logging was also change around the same time when the error started to come up.

**Comment by cburgdorf** [comment]
I tried to reproduce the error locally by running that test a ~~gazillion~~ 30 times but no luck.

```
pytest --count 30 tests/integration/test_trinity_cli.py -k 'test_does_not_throw_errors_on_short_run' --log-cli-level 0
```

Not a single occurrence of that error on my system.

**Comment by carver** [comment]
> I tried to reproduce the error locally by running that test a ~gazillion~ 30 times but no luck.
> 
> ```
> pytest --count 30 tests/integration/test_trinity_cli.py -k 'test_does_not_throw_errors_on_short_run' --log-cli-level 0
> ```
> 
> Not a single occurrence of that error on my system.

Hm, maybe something to do with the CI environment. Probably worth trying that line on an SSH'd CI instance.

**Comment by cburgdorf** [comment]
>Probably worth trying that line on an SSH'd CI instance.

Good point!

**Comment by pipermerriam** [comment]
> Also, isn't logging still using `multiprocessing` because I think logging was also change around the same time when the error started to come up.

No, I converted it to use a custom protocol in https://github.com/ethereum/trinity/pull/1277

**Comment by gsalgado** [comment]
@cburgdorf when reproducing those random failures locally I've had more success when using a high level of parallelization (e.g. `-n 8` or so). I've just tried it for this test a couple times and the first time I got a failure, but unfortunately I forgot to pass the `-s` flag so didn't get the log output :-/

**Comment by carver** [comment]
Hm, I wonder if you'll run into other kinds of failures. Right now, IIRC, the wheel tests are run with parallelism 1 in CI, so I'm not sure there are any guarantees that they will succeed if run in parallel.

**Comment by cburgdorf** [comment]
Alright, so I have tracked this error down to this [commit](https://github.com/ethereum/trinity/commit/ab04eaaec8ef9a708e15ebb4252d1a98b7ed9044). This is the first commit that ever sporadically fails with the `EOFError`

This is in fact the commit that changes the bootstrap of the components to be launched via the `asyncio-run-in-process` library. 

I verified this within a CI session as @carver suggested but others might have more luck reproducing it locally.

Here is how I did it:

1. Open a PR, let CI start, then use the "Rerun with ssh" feature of Circle and boot into the CI session.

2. Set the stage

```
git checkout ab04eaaec8ef9a708e15ebb4252d1a98b7ed9044
virtualenv venv
. venv/bin/activate
pip install -e .[dev]
pip install -e .[test-asyncio]
pip install pytest-repeat
```

3. Run the tests that should trigger the bug

```
pytest --count 10 tests/integration/test_trinity_cli.py -k 'test_does_not_throw_errors_on_short_run' --log-cli-level 0
```

This will take a while but with ten runs I always had at least one EOF error happening (which explains why this bug is so annoying!)

4. Next, checkout the previous commit.

```
git checkout HEAD~1
```

5. Run `pip install -e .[dev]` just to be sure

6. Repeat the tests.

```
pytest --count 10 tests/integration/test_trinity_cli.py -k 'test_does_not_throw_errors_on_short_run' --log-cli-level 0
```

You should see the test succeed with no errors.

I repeated that a several times and the behavior is consistent.

**Comment by gsalgado** [comment]
Ok, I thought I'd keep the momentum and have a go at this myself, and although I didn't managed to track it down I think I at least know where it's coming from:

- TrioIsolatedComponent and run_database_process() are the only places where we still use the multiprocessing package
- The db process seems to always start successfully, though, otherwise the components would report errors when trying to connect to it
- The only TrioIC component we have is PeerDiscoveryService, [introduced]( https://github.com/ethereum/trinity/commit/08892c9655cf807c0c2a2def7baa829572bb6a50) only 2 weeks before piper's change to use asyncio-run-in-process
- Logs always show a lot of consecutive timeouts for PeerCandidateRequest to the Discovery backend (which are handled by PeerDiscoveryService) when we get the EOFError, but that doesn't happen when there's no EOFError. That's a good indication the PeerDiscoveryService failed to start
- Couldn't find any of our dependencies using multiprocessing, so TrioIC is looking like the most likely candidate for the source of the error

Now, what really makes no sense to me is why we only started getting those errors once we switched to asyncio-run-in-process, because that only changed how we run AsyncioIsolatedComponents services and not TrioIC. FWIW, I also couldn't reproduce the EOFError on a checkout without the asyncio-run-in-process commit, even using a `--count=30` (which takes 1h to run)

**Comment by gsalgado** [comment]
I've also tried to come up with a simpler test to reproduce this (#1564), but so far had no luck

**Comment by carver** [comment]
> * The db process seems to always start successfully, though, otherwise the components would report errors when trying to connect to it

FWIW I have had sporadic issues with trinity locking on startup because the database process never becomes available. (Though I assume what you were getting at is that we don't see obvious database startup issues when `EOFError` is happening)

**Comment by cburgdorf** [comment]
I just had another `EOFError` with an interesting secondary error being reported. Not sure if related but dumping it here for further inspection.

```
   DEBUG  03-12 17:15:54  async_process_runner.py  b'Traceback (most recent call last):\n'
   DEBUG  03-12 17:15:54  async_process_runner.py  b'  File "<string>", line 1, in <module>\n'
   DEBUG  03-12 17:15:54  async_process_runner.py  b'  File "/usr/local/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main\n'
   DEBUG  03-12 17:15:54  async_process_runner.py  b'    exitcode = _main(fd)\n'
   DEBUG  03-12 17:15:54  async_process_runner.py  b'  File "/usr/local/lib/python3.7/multiprocessing/spawn.py", line 113, in _main\n'
   DEBUG  03-12 17:15:54  async_process_runner.py  b'    preparation_data = reduction.pickle.load(from_parent)\n'
   DEBUG  03-12 17:15:54  async_process_runner.py  b'EOFError: Ran out of input\n'
   DEBUG  03-12 17:15:54  async_process_runner.py  b'    INFO  2020-03-12 17:15:54,992  TrioIsolatedComponent  Process 3148 has already terminated\n'
   DEBUG  03-12 17:15:54  async_process_runner.py  b'    INFO  2020-03-12 17:15:54,992  TrioIsolatedComponent  Process 3148 has already terminated\n'
   DEBUG  03-12 17:15:54  async_process_runner.py  b'    INFO  2020-03-12 17:15:54,992  TrioIsolatedComponent  Process 3148 has already terminated\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'Traceback (most recent call last):\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'    "__main__", mod_spec)\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'    exec(code, run_globals)\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/asyncio_run_in_process/_child.py", line 260, in <module>\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'    parent_pid=args.parent_pid, fd_read=args.fd_read, fd_write=args.fd_write\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/asyncio_run_in_process/_child.py", line 187, in _run_process\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'    with os.fdopen(fd_write, "wb") as to_parent:\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'  File "/usr/local/lib/python3.7/os.py", line 1029, in fdopen\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'    return io.open(fd, *args, **kwargs)\n'
   DEBUG  03-12 17:15:55  async_process_runner.py  b'OSError: [Errno 9] Bad file descriptor\n'
```
