### ISSUE TITLE
How to actually benefit from ENR for better peer discovery?

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1442]
Soon we'll be fetching ENRs as part of node discovery, but in order to really benefit from that we will also need to change how `DiscoveryService` selects the nodes trinity should connect to.

I believe we still want to keep all nodes we contact (regardless of fork compatibility) in our routing table, so that we can be a decent p2p citizen. However, in our current implementation we use buckets of size 16 and when we try to add a node to a full bucket, those go into a replacement cache and will only get added to the routing table if the oldest node in that bucket is no longer responding. That means nodes that are compatible with us may never make it to the routing table and thus never be picked as connection candidates.

One way around that would be to get as many connection candidates we can from the ENR DB (which is separate from the routing table), and resort to the routing table only if we can't get enough from there. But I'm pretty sure that'd be a breach of protocol and may have security issues. Or maybe not, as long as we picked random ones from the ENR DB? One downside here is that we wouldn't try to connect to any non-ENR-enabled nodes that might be fork-compatible with us.

Another alternative would be to somehow prioritize nodes with ENRs when populating the routing table, and continue picking random ones from the routing table to use as connection candidates (although ignoring ones that are known not to be compatible).

A third option would be to not prioritize nodes with ENRs when populating the routing table and then, when picking connection candidates, use a mix of random known-to-be-fork-compatible entries from the ENR DB and random entries (with fork-compatibility unknown) from the routing table.

**Comment by pipermerriam** [comment]
My *ideal* scenario would be to architect this so that the pieces are as independent as possible.  Here's where the lines seem to draw themselves.

## Discovery

This is the part that manages the kademlia routing table, bonds with peers, and retrieves their ENR records.  This part would expose an API for something like:

- fetching random nodes from the routing table
- broadcasting information about ENR records over the event bus.

## Network DB

> Not necessarily the same as the current `network-db` component which could be scrapped if we think rebuilding something simpler is better.

This part manages persisting ENR records between runs.  It listens for information about new ENR records (typically coming from the Discovery service) and keeps track of them.

- listen for ENR record information sent over the event bus.
- querying ENR database for records.

---------------------------------------------------------------


My thought on the above is that it aims to keep the discovery component simple and constrained without business logic, and lets us write something more specific to handle the business logic of consuming, querying, and persisting ENR record information.

I'll leave it to you to decide the right way forward.  My preference would be to try and keep our discovery service free of ETH specific business logic if at all possible.

**Comment by gsalgado** [comment]
In your proposed solution, do you see us doing something like querying the `NetworkDB` for connection candidates first, and only if we don't get enough we fall back to querying `DiscoveryService`? 

Also, do you really think it makes sense for Discovery to broadcast ENRs over the event bus instead of simply storing them directly in a DB? Discovery would be the only one writing to that while others would just read.

**Comment by pipermerriam** [comment]
> In your proposed solution, do you see us doing something like querying the `NetworkDB` for connection candidates first, and only if we don't get enough we fall back to querying `DiscoveryService`?

I'm thinking that the query for candidates could hit both services and they both could respond independently.

**Comment by pipermerriam** [comment]
> Also, do you really think it makes sense for Discovery to broadcast ENRs over the event bus instead of simply storing them directly in a DB? Discovery would be the only one writing to that while others would just read.

I'm not 100% sure what is right here.  My thought was that we would want to do some extra data processing on the ENR records that might be application specific (like parsing fork ID's).  The discovery service probably should be unaware of the ETH chain and thus it wouldn't be able to process certain data.  Maybe we want a 2 layered approach where we have a RAW ENR record store and then we add a layer onto it to find nodes we like?  Not sure.  Feel free to try and see what works and draw the architecture lines wherever they naturally fall.
