### ISSUE TITLE
Ensure `apply_state_transition` exit condition

### ISSUE THREAD

**Issue by djrtwo** [ethereum/trinity#145]
### What is wrong?

See [#1631 review](https://github.com/ethereum/py-evm/pull/1631#discussion_r245773883)

`apply_state_transition` in its current form is not inherently guaranteed to exit.

### How can it be fixed

Replace the `while` logic in `apply_state_transition` with something like the following:
```python
for _ in range(state.slot, block.slot):
    ... # do loop
    if state.slot == block.slot:
        break
else:
    raise Exception("Invariant: ...")
```

**Comment by ralexstokes** [comment]
@djrtwo @pipermerriam do we still feel this is an issue?

while it isn't obvious (and therefore a bit unsafe), the `while` loop will terminate as long as `state.slot < block.slot` (reason: we increment state.slot by 1 every iteration of the loop body in `per_slot_transition`.) (so we could even just throw this assertion in there and call it day as it seems this is more a concern about programmer error, and not due to malicious input)

additionally, it seems that this function is not called unless we verify we have a parent block which implies that `state.slot <= block.slot`. i don't know if this implication is currently enforced by the code but we can easily imagine it can if it is missing.

if we take the above observations into account and still are uneasy w/ the `while` loop then i can modify it so that it is like the above...
