### ISSUE TITLE
Once more into the breach (Cross process DevP2P API)

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1464]
### What is wrong?

It is still too hard to interact with the devp2p network across processes.

The current model of replicating high level APIs over the event bus doesn't scale and is producing a maintenance burden that is hard to manage.

### How can it be fixed....

I think I finally have this worked out.... (conceptually).

In the main networking process we setup the standard `Connection -> Multiplexer -> Transport` stack.  Next, we attach a `Behavior` to the `Connection` which given an event bus, serves all of the *raw* messages that come through the transport over the event bus.

We write a new `TransportAPI` implementation which uses the event bus to listen for these messages for a given session and exposes them using the same transport API.

We should be able to then just hook this new transport implementation into the same `Connection -> Multiplexer -> Transport` stack in the new process and use it exactly the same way we would use it in the main process.

The missing piece here is the `PeerPool`.  For this I think we should pick the work from https://github.com/ethereum/trinity/pull/1095 back up.  We'll need to do something similar, exposing some base messages for peers joining and leaving the pool but I think we can replicate this API across the event bus pretty easily.

**Comment by cburgdorf** [comment]
>which given an event bus, serves all of the raw messages that come through the transport over the event bus.

Yeah, that seems like the right approach to me. My previous approach in https://github.com/ethereum/trinity/pull/721 tried to bridge events on a higher level which resulted in lots of boiler plate which was part of the reason why I abandoned it.

>We should be able to then just hook this new transport implementation into the same `Connection -> Multiplexer -> Transport` stack in the new process and use it exactly the same way we would use it in the main process.

This *sounds*  too good to be true :sweat_smile: 

>We'll need to do something similar, exposing some base messages for peers joining and leaving the pool but I think we can replicate this API across the event bus pretty easily.

We already broadcast `PeerJoined` / `PeerLeft` events across the event bus but #721 also had to deal with other nuances such as getting the peer metrics replicated across the processes. So that e.g. the sync (that would then run in another process) could pick the right peer to build the skeleton etc.

https://github.com/ethereum/trinity/blob/1a112b681a19f1321ac74588e4225aaf595d5dd5/trinity/protocol/common/peer_pool_event_bus.py#L226-L232
