### ISSUE TITLE
tests/integration/test_trinity_cli.py::test_shutdown_does_not_throw_errors fails intermittently

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1573]
Another one in the wheel-cli suite that fails intermittently. But this one is specially weird because there's no errors on trinity's logs:

```
tests/integration/test_trinity_cli.py::test_shutdown_does_not_throw_errors[command0] 
-------------------------------- live log call ---------------------------------
   DEBUG  02-24 23:09:01  async_process_runner.py  b'    INFO  2020-02-24 23:09:01,545               trinity  \n'
   DEBUG  02-24 23:09:01  async_process_runner.py  b'      ______     _       _ __       \n'
   DEBUG  02-24 23:09:01  async_process_runner.py  b'     /_  __/____(_)___  (_) /___  __\n'
   DEBUG  02-24 23:09:01  async_process_runner.py  b'      / / / ___/ / __ \\/ / __/ / / /\n'
   DEBUG  02-24 23:09:01  async_process_runner.py  b'     / / / /  / / / / / / /_/ /_/ / \n'
   DEBUG  02-24 23:09:01  async_process_runner.py  b'    /_/ /_/  /_/_/ /_/_/\\__/\\__, /  \n'
   DEBUG  02-24 23:09:01  async_process_runner.py  b'                           /____/   \n'
   DEBUG  02-24 23:09:01  async_process_runner.py  b'    INFO  2020-02-24 23:09:01,546               trinity  Started main process (pid=5144)\n'
   DEBUG  02-24 23:09:01  async_process_runner.py  b'    INFO  2020-02-24 23:09:01,548               trinity  Trinity/v0.1.0a34/linux/cpython3.6.10\n'
   DEBUG  02-24 23:09:01  async_process_runner.py  b'    INFO  2020-02-24 23:09:01,548               trinity  Trinity DEBUG log file is created at /tmp/tmpyqvy4a5i/trinity/mainnet/logs-eth1/trinity.log\n'
   DEBUG  02-24 23:09:02  async_process_runner.py  b'    INFO  2020-02-24 23:09:02,010           IPCListener  Starting <trinity._utils.logging.IPCListener object at 0x7fdfbc3f1e80> server over IPC socket: /tmp/tmpyqvy4a5i/trinity/mainnet/ipcs-eth1/logging.ipc\n'
   DEBUG  02-24 23:09:04  async_process_runner.py  b'    INFO  2020-02-24 23:09:04,071               trinity  Started DB server process (pid=5153)\n'
   DEBUG  02-24 23:09:10  async_process_runner.py  b'    INFO  2020-02-24 23:09:10,410             DBManager  Starting <trinity.db.manager.DBManager object at 0x7fcc15ba9fd0> server over IPC socket: /tmp/tmpyqvy4a5i/trinity/mainnet/ipcs-eth1/db.ipc\n'
   DEBUG  02-24 23:09:10  async_process_runner.py  b'    INFO  2020-02-24 23:09:10,448      ComponentManager  Starting components: JSON-RPC API/Network Database/Discovery/Upnp/Beam Sync Chain Execution/Beam Sync Chain Preview 0/Beam Sync Chain Preview 1/Beam Sync Chain Preview 2/Beam Sync Chain Preview 3/Request Server/Sync / PeerPool/TxComponent\n'
   DEBUG  02-24 23:09:11  async_process_runner.py  b'    INFO  2020-02-24 23:09:11,962      ComponentManager  Components started\n'
   DEBUG  02-24 23:09:35  async_process_runner.py  b'    INFO  2020-02-24 23:09:35,011      DiscoveryService  Preferred peers: (<Node(0x1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303)>, <Node(0x78de8a0916848093c73790ead81d1928bec737d565119932b98c6b100d944b7a95e94f847f689fc723399d2e31129d182f7ef3863f2b4c820abbf3ab2722344d@191.235.84.50:30303)>, <Node(0xddd81193df80128880232fc1deb45f72746019839589eeb642d3d44efbb8b2dda2c1a46a348349964a6066f8afb016eb2a8c0f3c66f32fadf4370a236a4b5286@52.231.202.145:30303)>, <Node(0x3f1d12044546b76342d59d4a05532c14b85aa669704bfe1f864fe079415aa2c02d743e03218e57a33fb94523adb54032871a6c51b2cc5514cb7c7e35b3ed0a99@13.93.211.84:30303)>)\n'
   DEBUG  02-24 23:09:35  async_process_runner.py  b'    INFO  2020-02-24 23:09:35,019      DiscoveryService  Node details changed, generated new local ENR with sequence number 1\n'
   DEBUG  02-24 23:09:35  async_process_runner.py  b'    INFO  2020-02-24 23:09:35,020      DiscoveryService  Running on enode://42c8aad4d28af2902e1f39f469f368c5ba52e098dec15a7882b92357601ab3a0323264bbe31394fafcfbd11e1bcab7835853739d449dfbc7b41fadf31e4f4d9d@0.0.0.0:33365\n'
FAILED                                                                   [ 82%]
```

https://circleci.com/gh/ethereum/trinity/194498?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by cburgdorf** [comment]
That's a special form of flakyness here.

https://github.com/ethereum/trinity/blob/f96571654d983c7c97530d855593df1f94adc04e/tests/integration/test_trinity_cli.py#L356-L359

This test ensures that Trinity shuts down cleanly. However, Trinity does not shut down cleanly and so the test is an `xfail` with the intention that at one point it starts failing and we remove the `xfail` so that it actually turns into the test that keeps our shutdowns clean.

Whenever this test starts failing it means that our shutdowns get cleaner. The fact that it is now becoming flaky probably links back to some recent fixes @carver did regarding beam sync hangs.

In the past, whenever this test started failing we just tried to be even more picky about what we considered to be a clean shutdown. So we added things like `ResourceWarning` to the list of things that fail the test.

https://github.com/ethereum/trinity/blob/f96571654d983c7c97530d855593df1f94adc04e/tests/integration/helpers.py#L19-L26

My first thought was: *Nice, maybe we are at a point where we can remove the `xfail` and don't be too harsh on `ResourceWarning (remove it from the list)*. So that would only leave hard errors to be detected and fail the test. But unfortunately we aren't at this point yet. We still get hard mistakes more often than clean shutdowns.

I'm running out on ideas what to do here. To recap, this test becoming flaky means our shutdowns are becoming cleaner but obviously we don't want flaky tests. Maybe we just have to deactivate the test for now and turn it back on when we do actually have somewhat clean shutdowns?

**Comment by carver** [comment]
> The fact that it is now becoming flaky probably links back to some recent fixes @carver did regarding beam sync hangs.

Yup, sounds very plausible.

> I'm running out on ideas what to do here. To recap, this test becoming flaky means our shutdowns are becoming cleaner but obviously we don't want flaky tests. Maybe we just have to deactivate the test for now and turn it back on when we do actually have somewhat clean shutdowns?

Agreed. With the already flaky `EOFError` bug, I can't stand adding another one. :+1: for switching `xfail` to `skip`, and adding an issue to reactivate it. (Maybe add the issue to the beta milestone?)

**Comment by cburgdorf** [comment]
We can close this as we have temporary disabled the test
