### ISSUE TITLE
Backfilling block bodies during Beam Sync

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1665]
### What is wrong?

Currently, during Beam Sync, Trinity cannot answer any questions about transactions, receipts, or uncles that happen in blocks that were not executed. (Actually, currently, Beam Sync never terminates)

### How can it be fixed

Somewhat similar to #1664 - we could start tracking the missing block bodies in a list of ranges by block number. Then add a service that downloads block bodies (probably only when the Beam Sync lag isn't too high).

This could be very similar (or potentially even reuse) the code from the fast syncing approach, here:
https://github.com/ethereum/trinity/blob/1b32d85b1065d6c97de16887a0433b0a3e675fe7/trinity/sync/full/chain.py#L578

The main difference is that you would replace the header syncer passed in here: https://github.com/ethereum/trinity/blob/1b32d85b1065d6c97de16887a0433b0a3e675fe7/trinity/sync/full/chain.py#L133

with a "header syncer" that just loads the headers that already exist out of the database.

There is some crossover that has to be managed with #1664 -- what if the header is missing because of a checkpoint. The simplest thing to do, I suppose, is to pause this backfiller until the header shows up.

**Comment by cburgdorf** [comment]
Ignoring potential holes due to checkpoint syncing for a moment, do we currently have simple markers in our DB that remembers the highest block number for which have downloaded a consecutive chain of `receipts`, `uncles` and `transactions`?

This came up while working on tracking (https://github.com/ethereum/trinity/pull/1682) because `geth` can tell at any point: What is the latest header, block and receipt that we have synced so far. 

Maybe it would make sense to have markers like you proposed in #1664 for uncles, transactions and receipts individually? And maybe it would also make sense to come up with a special unbounded marker. For instance, when we start beam syncing and we haven't downloaded any uncles, receipts or transactions than e.g. `MISSING_RECEIPTS_NUMBERS` would contain something like `[[0, -1]]` which would basically mean we are missing everything from `0` to infinity.

When we then start backfilling from genesis and e.g. stop after `999 we would update it to `[[1000, -1]]`.

Does that make sense? And related, do you have already started working on this and is this an area where you'd think I could help with?

**Comment by pipermerriam** [comment]
I believe that we don't track this and that it should not be part of py-evm so I believe it's something that trinity would need to keep track of.  It could still store it in the main key/value database.

**Comment by carver** [comment]
> Does that make sense? 

Yeah, most of it!

> Maybe it would make sense to have markers like you proposed in #1664 for uncles, transactions and receipts individually?

So I guess the win here would be that: if you download some of these things from a peer, but didn't get them all persisted yet, that you can pick up where you left off without downloading them?

I think the benefit of not having to download some data from a peer again is smaller than the cost of the extra code to handle the case of loading the transactions/uncles/receipts from disk in some intermediate pre-block-persistance store. (Plus some added DB read/write costs there)

I think it's better to just load them all from the peer, and run `persist_block()`, then mark that complete block as persisted (which includes the uncles, transactions and receipts).

> And related, do you have already started working on this and is this an area where you'd think I could help with?

I haven't really started in on it, if you want to take a stab, be my guest!

**Comment by cburgdorf** [comment]
> think the benefit of not having to download some data from a peer again is smaller than the cost of the extra code to handle the case of loading the transactions/uncles/receipts from disk in some intermediate pre-block-persistance store. 

No specific reason other than, if it can be tracked individually, maybe we will need the granularity at one point. But no objections to keeping it simple and just track whole blocks :+1: 

>I haven't really started in on it, if you want to take a stab, be my guest!

Awesome! I'll start digging!
