### ISSUE TITLE
Why is MIT license selected?

### ISSUE THREAD

**Issue by raisty** [ethereum/trinity#1734]
* Trinity version: v0.1.0-alpha.35
* OS: osx
* Python version (output of `python --version`): 2.7.16
* Environment (output of `pip freeze`): _not related_

### What is wrong?

MIT license used in the project.

### How can it be fixed

Please, elaborate on - why MIT license was chosen?

Maybe it can be fixed with changing the license to LGPLv3 as go-ethereum have this license.

**Comment by cburgdorf** [comment]
We default to MIT license in our projects. I think our general line of thinking is "take this software and do with it whatever you want.". 

Is there a specific problem you are facing? As far as I think you can easily take code from Trinity and use it in `go-ethereum` or even in any closed source software. 

I'm not sure if it works the other way around (take code from Geth, use it in Trinity). But I would say that is the very reason why we haven't chosen a different license because we deliberately want that people can use our code for whatever they want.

Disclaimer, this is my personal opinion and @pipermerriam, @carver or others may have a different opinion on this.

**Comment by raisty** [comment]
Thank you, Sir, for your personal opinion. I appreciate your answer.

> I think our general line of thinking is "take this software and do with it whatever you want.".

I really like your slogan and the way you are going.

Unfortunately, the slogan of GPL is:

> Free as in Freedom

Which is not the same and can cause some difficulties in point of view licensing.

I want to be sure any user can use your software without any harm (including licensing issues).

IMHO:

1. The software should care about the security of users and final impact
1. We cannot change GPL to non-GPL license

**Comment by cburgdorf** [comment]
>I want to be sure any user can use your software without any harm (including licensing issues).

I'm not a lawyer but as far as I can think anyone can use our MIT-licensed software and use it for **anything** including building a closed source, overly expensive product that turns out to kill half of the planet while simultaneously making the rich people richer in which case I will be very sad but still can't do anything about it (except from withdrawing my resources in protest)

Do you have a concrete issue to solve where you think the licenses are in conflict? The only thing I can think of is that we might not be able to accept code that is copied from `go-ethereum` in this code base but that would be an issue of LGPLv3 not allowing MIT licensed software to use their code.

But if, for instance, you want to use the Trinity code base to build another product and include `go-ethereum` code, [you should be free to re-license](http://vschart.com/compare/lgpl3/vs/mit-license) your Trinity-based project under LGPLv3 I think. That being said, I'm out of my comfort zone here and this is my laymen perspective on it. :)

**Comment by raisty** [comment]
Well, we have probably many views on how we see this issue.
I, personally prefer factual view on any issues.

But yes, I am not a lawyer also.
I discuss the topic of licensing with plenty of lawyers in my life and my personal choice is WTFPL license.

I think for the seek of comfortability and ensure that your project can be used in a production environment you need lawyer opinion.

Still, my second opinion stays the same: We cannot change GPL to non-GPL.
Even your link declares it clearly.

But appreciate your comment. Very useful to hear other minds about this topic.
Not so many people can contribute in this issue overall.

**Comment by pipermerriam** [comment]
We won't be changing the license on this project.  MIT is extremely permissive and the effort to re-license is high and would provide us with little added value.

**Comment by raisty** [comment]
Thank you for your information as a member of the Ethereum team. Then I assume any fork of Ethereum (licensed under LGPLv3) can hold MIT license. It will be beneficial to declare it on the website also. It can answer a lot of questions. I appreciate your answer Sir, it is very valuable.
