### ISSUE TITLE
Replicate ganache --fork functionality

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1793]
### What is wrong?

This depends on  #69 (`--dev` mode). I think one use case where Trinity could really shine is to replicate the behavior of `ganache --fork` where one can setup a node for development that acts a fork of e.g. mainnet and hence allows one to develop directly against all mainnet contracts etc.

This is a feature request that was [raised in the Py-EVM chat](https://gitter.im/ethereum/py-evm?at=5ee880cd49260560aa6361ac)

I think Trinity is well equipped for this because of its beam sync functionality that allows us to interact with the tip of any chain within moments.

### How can it be fixed

- We first need a basic dev mode (see #69)
- After we have that I guess the steps would be roughly to figure out how to combine dev mode with pseudo beam syncing a selected network (e.g. mainnet)

**Comment by carver** [comment]
Hm, as much as possible, it would be nice to support this without custom Trinity hooks, like ganache does by just making backend calls to Infura (I assume that's how it works).

The tricky part is to support this during Beam Sync, even after the block where the state was forked starts to get old. At that point, peers drop the state trie, and stop responding to `GetNodeData` calls for that trie.

In fact, after thinking a bit more... it seems this is not possible to do (in general) during Beam Sync. For example, if:
1. you fork a `dev` block N
2. a contract has storage, but no reads or writes on mainnet since before block N
2. a contract gets destroyed on mainnet block >N
3. you wait more than 75 blocks (or whatever it is), to have peers drop the old state trie nodes
3. you make a call to your dev chain that retrieves the contract's storage
4. FAIL -- the storage wasn't retrieved by beam sync, and no peers can/will give it to you

**Comment by cburgdorf** [comment]
Good point! In fact, `ganache --fork` suffers from the same issue (at least when not used against an archive node). When I was using it against my local dappnode (`fast` synced, pruned) I noticed that after a while I'd run into missing tree nodes for calls that used to work before.

But I wonder if something like this could be done to mitigate it:

1. Maintain two chains in parallel, one that is actively beam syncing the base network (e.g. `mainnet`) and one that has forked off at some point and mines development blocks whenever it is given local transactions.

2. Then, whenever it is needed (vagueness is on purpose) we would rebase the development fork on top of the tip of of the "active" chain. In other words, we fork again at the tip and replay/rebase all the development blocks on top of the new fork. 

Well this is basically like restarting `ganache --fork` whenever the missing tree nodes come up and hence it will cause some disruption to the work flow (e.g. deployed contract addresses change) but maybe some of the disruption can be mitigated and then it becomes slightly more convenient then restarting `ganache --fork` whenever things crumble :)

**Comment by carver** [comment]
> When I was using it against my local dappnode (`fast` synced, pruned) I noticed that after a while I'd run into missing tree nodes for calls that used to work before.

Ah, interesting!

> it will cause some disruption to the work flow (e.g. deployed contract addresses change)

Yeah, I can't imagine how we could do the chain rebase automatically, because of issues like this. But when the client reports a `MissingTrieNode` that can't be recovered from peers\*, we can suggest that they invoke the "dev-chain rebase" manually. Hopefully it won't be too disruptive, because they'll deploy from a fake account that doesn't have its nonce changing on mainnet, so the contract addresses won't change on a rebase. But there definitely could be changes in your dev chain (if your init code depends on the state of other contracts, for example).

\* This is a bit trickier than it sounds to even figure out. It's generally impossible to tell the difference between peers that are rate-limiting you by returning empty responses to `GetNodeData`, or are still syncing, or have deleted the node hash because it is garbage-collected. I think our only real option is a timeout, so we will sometimes give "false-positive" indications that a chain rebase might help. Checking the chain gap between the fork block and the tip is one way to improve the situation. There is no point in recommending a rebase if the fork was only 10 blocks ago, for example.

**Comment by cburgdorf** [comment]
>Hopefully it won't be too disruptive, because they'll deploy from a fake account that doesn't have its nonce changing on mainnet, so the contract addresses won't change on a rebase

Yeah, or maybe clever deployment tooling can simply create ENS names on the fly for every deployed contract. But that goes far beyond what Trinity should be concerned about.

>Checking the chain gap between the fork block and the tip is one way to improve the situation. There is no point in recommending a rebase if the fork was only 10 blocks ago, for example.

Yeah, detecting the when to suggest a rebase sounds like a tricky thing to do but even just being able to do it as soon as a `MissingTreeNode` comes up would be a handy thing I guess.

**Comment by carver** [comment]
> Yeah, or maybe clever deployment tooling can simply create ENS names on the fly for every deployed contract. But that goes far beyond what Trinity should be concerned about.

Ooh, I like this! I like that it reminds people to think about ENS from the start, and helps them get used to using names everywhere instead of hex addresses. And yes, it's another reason that some/most of this functionality should live in eth-tester.

> even just being able to do it as soon as a `MissingTreeNode` comes up would be a handy thing I guess.

Hm, with beam sync, that exception just means that we need to go ask a peer for it. It's just a normal scenario of "we don't have that part of the trie yet." We avoid this problem of asking peers for nodes that are too old by proactively pivoting beam sync if we fall too far behind the tip.
