### ISSUE TITLE
Header syncer seems to race ahead

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1820]
### What is wrong?

The debug logs seem to suggest that the header syncer is racing way ahead of the body downloads, at least when doing a full sync. The intended behavior is for the header syncer to only go a few thousand ahead of the tip, during sync.

### How can it be fixed

Just requires some investigation. Probably something to do with the capacity check being in the wrong place, or not getting triggered/cleared correctly.

**Comment by cburgdorf** [comment]
I'm not sure if this is related but it might be:I would imagine that if you pass a `HeaderSyncerAPI` to the `BaseBodyChainSyncer` which simply yields a finite set of headers, then eventually the `BaseBodyChainSyncer` would go and fetch blocks and receipts and  persist these 100 headers. But that is not the case, it never makes it through the whole set of headers if it is finite. This doesn't seem to be a problem in reality because the headers aren't finite in practice (well, except for the gap syncer that I'm working on) and so there are always new headers coming in that eventually push things through.

I'm still debugging why it behaves that way and there's a good chance that this is by design but I wanted to leave this comment just in case it is an actual bug and might be related.

**Comment by cburgdorf** [comment]
Ah, wait, I think the behavior I described was caused by me misconfiguring something, so nothing to see here.
