### ISSUE TITLE
Trinity doesn't seem to advertise its version number to other clients correctly

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#2036]
### What is wrong?

Just looking at https://ethernodes.org/nodes it seems like Trinity doesn't announce its version correctly to other clients.

![image](https://user-images.githubusercontent.com/521109/92732872-515e1700-f377-11ea-9305-e34793979e55.png)

### How can it be fixed

Needs to be looked into.

**Comment by Elnaril** [comment]
On https://www.ethernodes.org, I noticed that on all nodes where the version is not 0.0.0 (at least those I checked), there is a dash (-) between the vX.Y.X and the attached string if any. For example on a parity-ethereum client: v2.5.13-stable-253ff3f-20191231 , there a dash between v2.5.13 and stable. See screenshot below:

![image](https://user-images.githubusercontent.com/57373038/101057838-66b49d00-3584-11eb-9ada-2383aa6e7bad.png)


So, I did the following trick. I replaced line 16 below 
https://github.com/ethereum/trinity/blob/8ba31bfb13082062993d2019d8a0cfa1af97c532/trinity/_utils/version.py#L8-L20
by:
![image](https://user-images.githubusercontent.com/57373038/101059086-cd868600-3585-11eb-9096-1131582d3e0a.png)
So that my Trinity node advertises now the following version:
![image](https://user-images.githubusercontent.com/57373038/101059319-09215000-3586-11eb-8c9d-ae72a1abb98d.png)

and a few minutes later I could see on https://www.ethernodes.org that the version 0.1.0 is shown:

![image](https://user-images.githubusercontent.com/57373038/101059551-4ede1880-3586-11eb-8f5c-1c64bdab375c.png)
![image](https://user-images.githubusercontent.com/57373038/101059630-661d0600-3586-11eb-901d-abdf75e097b4.png)

Moreover, I had a quick look to https://www.python.org/dev/peps/pep-0440/#pre-releases but could not find any naming convention suggesting a package name in alpha version should separate the numerical component from the pre-release alphabetical identifier with a dash or some other separator.

So except if there is some other convention I'm not aware of or if we want to comply with what seems to be a constraint of ethernodes.org, I would say that there is no actual issue with Trinity.
