### ISSUE TITLE
Maintain updated pool of recommended peers

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#24]
### What is wrong?

Quick brain dump from https://github.com/ethereum/py-evm/pull/744#discussion_r190291371

Trinity currently uses a hardcoded list of recommended peers + discovery protocol. It would be nice to maintain a list of recommended peers based on the following metrics that also survives restarts (persisted in db / config file).

Metrics:

* latency
* correct responses (doesn't send unexpected data)
* num success/failed requests

### How can it be fixed

Initial idea is to have some sort of `PeerSubscriber` API which would be given a view into peer requests and responses and then to aggregate that data into some accessible form. Then the a `FancyPeerPool` class could use this data to inform what nodes/peers it returns.

**Comment by carver** [comment]
This should use the new sqlite database, presumably. After a long, slow ramp-up period of collecting peers, it would be nice to attempt to reconnect to those peers right away after rebooting `trinity`.

**Comment by carver** [comment]
FWIW, this should probably not add inbound peers as preferred, since it would "convert" an inbound peer to an outbound peer on restart, opening another eclipse attack avenue.

---

If we wanted to be really fancy, we could store inbound nodes in a separate list. Then we would only connect to them after we have enough outbound peers and "pretend" they were inbound for all analytical purposes. The converse of this mechanism could also be helpful: if we found a peer in the past and they re-dial us, we could treat them as outbound still for eclipse purposes. This is all potentially hairy and error prone, so probably belongs in a separate low-priority issue.

**Comment by pipermerriam** [comment]
I think we should only populate the database with outbound peers, and inbound peers are strictly excluded.

As for treating a known outbound peer that dials inbound as outbound, I think we should avoid conflating these two concepts.  Inbound/Outbound connection labeling should probably be purely based on which side the connection was initiated from.  For tracking purposes, we can have meta information like `first_connection_direction: <dial-in/dial-out>` to track the origin of how we learned about the peer.

**Comment by veox** [comment]
In issue #501 I argue that even having "default preferred peers" goes against the principle of least surprise.

If a node operator doesn't specify any preferred nodes, than no known peers should have elevated status.
