### ISSUE TITLE
How to access the p2p module of trinity only

### ISSUE THREAD

**Issue by rbval** [ethereum/trinity#378]
* py-evm Version: py-evm==0.2.0a42
* OS: osx
* Python Version (python --version): 3.6

### What is wrong?
I used to use the `p2p` module directly from `py-evm`. Since `py-evm` was upgraded to a38, it seems that `p2p` has been moved to the `trinity` project. 

Running `pipenv install` in a fresh environment with the following Pipfile:
```
[packages]
trinity = "*"
web3 = "*"

[requires]
python_version = "3.6"

[pipenv]
allow_prereleases = true
``` 
results in the following error:
```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches websockets<8.0.0,==5.0.1,>=7.0.0
```

### How can it be fixed

I have no idea how I should approach this. I basically need the p2p module only that you have specified in the `setup.py`. Is there a way I could access that through `pipenv` / `pip` install directly?

**Comment by ralexstokes** [comment]
the conflict you are seeing is because `web3.py` wants a later version of `websockets` than the one specified in `trinity`.

`trinity` does pull in `web3.py` as a dependency so if you don't need a specific version then you could try removing the line `web3 = "*"` from your `Pipfile` and I suspect it will work. (you should still end up w/ `web3.py` in your deps.

that is a bit of a workaround, however.

i'm not sure if we want to split `p2p` into a library separate from `trinity` @pipermerriam @carver @cburgdorf will have more to say on that.

an intermediate solution is to just raise the `websockets` version in `trinity`.

**Comment by pipermerriam** [comment]
Currently the `websockets` library is only used as part of the `ethstats` plugin so I think we have a few options.

1) loosen the version range requirement (as a temporary solution)
2) look into moving the eth-stats plugin out of the main codebase into it's own package.
3) just bump the version to match `web3.py`

**Comment by carver** [comment]
> i'm not sure if we want to split `p2p` into a library separate from `trinity` @pipermerriam @carver @cburgdorf will have more to say on that.

On this point, yes it's an eventual goal, but we're a ways away from having a public `p2p` API that we're happy with. I suspect it will change significantly before we split it out.


> 1. loosen the version range requirement (as a temporary solution)
> 2. look into moving the eth-stats plugin out of the main codebase into it's own package.
> 3. just bump the version to match `web3.py`

Yup, option 2 sounds good, although I think I would accept a PR with 3 as a temporary solution since I'm not sure anyone feels urgency to do 2. Not sure we check eth-stats in any tests, though, so it should ideally come with assurance that a manual test was run. (I suspect @cburgdorf will be interested in doing 2, but he's in the middle of a substantial project)

**Comment by cburgdorf** [comment]
Maybe one repository with (community) trinity plugins would make sense. Still every plugin would be an entirely different `pip` package but all grouped in one mono repository. One repository per plugin may become a maintenance horror if trinity plugins by the community become a thing (hopefully!). Plus, having one shared repository also helps with discoverability of these plugins. Thoughts?

**Comment by pipermerriam** [comment]
Mono-plugin repo :+1:
