### ISSUE TITLE
neighbor's table polluting attack

### ISSUE THREAD

**Issue by z3roTo0ne** [ethereum/trinity#453]
hello developers, I found an bug on discovery.py, I just send Ping and Pong, then the  node  reminding "DiscoveryProtocol  unexpected v4 * "  but still add the some dirty data to the neighbor's table, so I can pollute the neighbor's table easily.

I also can send_neighbours data to pollute the neighbor’s table, and then it's filled with the number of connections, so others cannot connect to the node
[image](https://user-images.githubusercontent.com/28896669/54909393-110d9d80-4f25-11e9-9540-622ef2397385.png)

**Comment by lithp** [comment]
Hi z3roTo0ne, nice catch, and thanks for reporting this! I'll take a look at it.

Out of curiosity, what are you using to manually send `Ping` and `Pong` and `Neighbors` packets?

**Comment by z3roTo0ne** [comment]
I pretend to be a node, and then rewrite discovery_protocol, using asyncio module to send send_ping_v4 send_pong_v4 pong, send_neighbours_v4

**Comment by z3roTo0ne** [comment]
Hi, Has this issue been confirmed? I want to apply for a cve number

**Comment by lithp** [comment]
Sorry for taking so long at this! I'll look at it soon. I doubt this is worthy of a cve number, trinity is still alpha software and I think at most 3 trinity nodes are running at any given time, almost certainly 0 of them are being relied on to feed a business trusted data.

**Comment by lithp** [comment]
Okay, I apologize again for taking a while to respond, especially since I'm coming back with a question. Could you give some more detail on the problem please? I wrote a test case for I problem I thought you were describing, but it passes:

```python
# in tests/p2p/test_discovery.py
def test_ignore_unsolicited_neighbours(alice, bob):
    link_transports(alice, bob)

    shamir = NodeFactory()

    alice.send_neighbours_v4(bob.this_node, [shamir])
    assert not shamir in bob.routing

    # bond alice to bob
    bob.update_routing_table(alice.this_node)

    # even though they're bonded this message should be dropped
    alice.send_neighbours_v4(bob.this_node, [shamir])
    assert not shamir in bob.routing
```

I looked at `process_neighbours` and it appears to do the correct thing, which is drop packets it isn't expecting. Did I understand you wrong? I think the problem you described was as follows?

1. Alice sends Ping to Bob
2. Bob sends Pong to Alice
3. Alice sends Neighbours to Bob
4. Bob has those neighbors in its routing table, even though it didn't ask for them.

**Comment by lithp** [comment]
@z3roTo0ne I'm going to close this issue, but feel free to re-open it if you think I've misunderstood you! And if Github doesn't let you re-open just drop a comment here and I'll open it again for you.
