### ISSUE TITLE
Remove fast sync option

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#511]
### What is wrong?

The current plan is to dump fast sync altogether, in favor of whatever protocols come next. The current fast sync implementation is incomplete, so should probably be removed entirely. (maybe not immediately, but probably before going beta).

### How can it be fixed

- [ ] Remove the `--sync-mode fast` option
- [ ] Remove dead code
- [ ] Remove documentation references, if any (except probably a note specifically saying it's not implemented)

**Comment by veox** [comment]
> Remove the `sync-mode` option

But there is still "light" sync. Or is that dropped also?

**Comment by carver** [comment]
Ah, I meant to remove the `--sync-mode fast` option. I'll update above.

**Comment by cburgdorf** [comment]
My current understanding was that the firehose sync would only tackle the state sync so that the overall principle of the fast sync remains the same and only once we get to the point where we want to sync the state, we would use this new different sync method.

But this issues sounds as if we ditch the entire fast sync including the SkeletonSyncer etc. Regarding the work of moving the sync and the request server into isolated plugins, I'm still blocked on some work that is currently going into lahja (https://github.com/ethereum/lahja/pull/42) so I guess I will just hold off with that work until the event bus is ready and then sync back with you to see how we should proceed.

**Comment by carver** [comment]
Ah, so the skeleton syncer still feeds headers into beam sync (it also feeds headers into full sync).

**Comment by veox** [comment]
I think this was closed by PR #1084.
