### ISSUE TITLE
Make file logging respect individual log level increase

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#689]
### What is wrong?

On current master, it is not possible to reduce the general log level to e.g. `ERROR` but increase the log level for one specific module e.g. set `p2p.discovery` to `DEBUG2`.

With #682 this becomes possible at least for stderr logs. E.g. the following works as expected:

`trinity -l ERROR -l 'p2p.discovery=DEBUG2'`.

For `stderr` this does only print `ERROR` logs for everything except `p2p.discovery` where also `DEBUG2` logs or higher are printed.

For the file log this will only print `ERROR` because it is currently not possible to increase log level of individual modules above the general file log level.

### How can it be fixed

1. Probably some sort of re-attaching log handler magic inside https://github.com/ethereum/trinity/blob/9fe8fa87689428608f76eefb4415c85dc28ff646/trinity/_utils/logging.py#L103-L108

2. Enable the test currently commented test case https://github.com/ethereum/trinity/blob/38cc2bb2119104030f3ec54e2022932fc73c293f/tests/integration/test_trinity_cli.py#L208-L219

**Comment by jannikluhn** [comment]
For some tests I did a while ago I used a simple YAML file in conjunction with [logging.config.dictConfig](https://docs.python.org/3.8/library/logging.config.html#logging.config.dictConfig) to configure logging (see https://github.com/ethereum/trinity/pull/1033/files#diff-efaf22e24a01e85cc46fa436ca244817R11-R25 and https://github.com/ethereum/trinity/pull/1033/files#diff-69674a1dd689a764b5421acc5f5b24b2R1-R35).

This turned out to be quite useful for debugging because editing a YAML file is much easier than a multi-line CLI command if one wants to specify lots of options (at least for me). Also, one can quickly switch between multiple very different configurations (e.g. for a client or a server). Because of `dictConfig` it's also maximally powerful, e.g. one can also change the formatting.

Not suggesting this to be the only option, but as an additional option this could be very helpful.

**Comment by pipermerriam** [comment]
I could see allowing this via something like `--logging-config`.  We'd probably want some logic that would detect duplicates between the supplied logging config and the command line flags for logging.  Also probably allow command line flags to override things in the config file.  And last, if there are duplicates between the config file and the CLI flags, we probably want to log those during application startup.  :+1:

**Comment by cburgdorf** [comment]
I think that at some point we want a general config file for Trinity anyway. Not only for logging also for all kind of other things like preferred peers, max peers etc.
