### ISSUE TITLE
Backfill cold state during Beam sync

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#854]
This issue is to track some ideas on how to fill in cold state with beam sync.  Mostly a brain dump that hopefully works towards some good ideas.

## Goals

1. Preserve full node caches.
2. Swarming: syncing nodes should be able to serve other syncing nodes with some reasonably good probability.
3. Fill in all cold state within a reasonable amount of time.

In order to have a cache preserving behavior clients need to be pulling *common* state.  i.e. two clients that are beam syncing at the same time should end up pulling roughly the same cold state nodes.  Ideal case is for this property to hold even if one of the clients started their sync at a very different time than the other.

## Questions

- Is it beneficial to prioritize filling in the account state before filling in the contract state?

There might be an argument that account balances and nonces are more valuable information than the actual contract code and state.   Every contract call interacts with the account but doesn't necessarily interact with the state (but it does require the actual code).

### Prioritize cold state reads from alternative sources like Swarm.  

When looking up cold state, we could try to prioritize fetching it from alternative sources such as Swarm.  This could help preserve full node caches while having the beneficial side effect of keeping cold state active in the swarm network.

### Select cold state based on most recent processed block

In order to have multiple syncing clients converge on fetching the same state nodes we could use the most recent block's state reads as the locus for clients to swarm around.  Something like traversing the state trie outwards from the nodes that were read in the most recent block till it finds the closest account that it is missing and fetches it too.  The same procedure could be used for contract state.

This should have the following effects:

- clients asking for data from full nodes will be asking for mostly the same data from the same part of the trie.
- a client that is syncing should always be able to serve a state request to another client provided that the requesting client started syncing *after* them.

**Comment by carver** [comment]
I thought we had an issue for this, but couldn't find it. Making this the "official" one for now. Forward progress is blocked on (actively progressing) https://github.com/ethereum/py-trie/pull/95.

**Comment by carver** [comment]
I can't remember where the proposal is that suggested a 65 bytes index (account + subtrie identifier + subtrie index) -- where subtrie can only be storage for now. So I'll just write out a though I had about it here:

Anything beyond the 32 bytes is pretty useless, because there's effectively 0 chance that you will land directly inside an account with the first 32 bytes. I guess the trailing 32 bytes could mean that the subtrie index somehow applies to the nearest account. Even then, it's very unlikely to help with accounts like IDEX, because you're extremely unlikely to land *immediately* adjacent to the few giant accounts with the first 32 bytes, so you would still end up scanning them sequentially. There would be issues that it would take longer to eventually land near enough the giant accounts to collect all their storage.

So I think we still don't have a good "random selection" story that deals with accounts that have giant storage.
