### ISSUE TITLE
Beam Sync: pivot to latest block if the lag gets too high

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#908]
### What is wrong?

If Beam Sync lags behind far enough, then it stops being able to sync. Sync fails because peers no longer have the necessary trie nodes.

### How can it be fixed

Unfortunately it's difficult to strictly define that this scenario has occurred, because peers are permitted to return empty results when requesting trie nodes. It could be a peer that is overloaded, or just recently started syncing, or that the local peer has fallen too far behind.

Likely, we'll need to measure the lag from the tip, or the time lag, and use that to decide that we have fallen too far behind. At that point, we would simply skip over importing the remaining blocks in between the last imported block and the tip, and re-start beam sync from the tip again. This should all happen without intervention.

**Comment by carver** [comment]
I'm not certain this belongs in the MVP, just adding it for visibility, and maybe we will remove it again.

**Comment by pipermerriam** [comment]
I think we could get reasonably reliable results if we define the need to pivot as:

1. no forward progress of syncing state after some timeout
    - all peers fail at returning needed nodes
    - maybe confirm by checking the actual block state-root node is also not available
2. state root of newer blocks is available
    - at least one peer does return non-empty state requests for "new blocks"

This allows us to a) detect the stall condition which I think can be done semi-reliably now and b) confirm that peers will return data for newer blocks (as defined as them being willing to return the node data for a fresh state root.

**Comment by pipermerriam** [comment]
(this is probably more complex than is absolutely necessary but I want to document it).

If we define an integer `BEAM_WINDOW` which is the number of blocks from the known chain head, we can calculate the probability that we will fail to import or preview a given block.  It seems like this might be a good metric to determine if we should pivot.  This would allow us to pivot before starting a preview or import rather than timing out in the middle which might be uglier.

- `BLOCK_TIME` is the average block time measured over recent history.
- `BLOCK_STDEV` is the standard deviation of the block time over recent history
- `IMPORT_AVG` is the average time it takes to import a block
- `IMPORT_STDEV` is the standard deviation
- `PREV_AVG` is the average time it takes to import a block
- `PREV_STDEV` is the standard deviation.

We can compute an upper bound on block times with:

- `MAX_EXPECTED_BLOCK_TIME = BLOCK_TIME + 3 * BLOCK_STDEV`

We can determine an upper bound on import or preview time via with 99.9% likelyhood as:

- `MAX_EXPECTED_IMPORT_TIME_IN_BLOCKS = (IMPORT_AVG + 3 * IMPORT_STDEV) / MAX_EXPECTED_BLOCK_TIME` for import
- `MAX_EXPECTED_PREV_TIME_IN_BLOCKS = (PREV_AVG + 3 * PREV_STDEV) / MAX_EXPECTED_BLOCK_TIME` for preview

Compute `PIVOT_POINT` which is the observed chain head minus `BEAM_WINDOW`.

For a given block number that we are considering previewing or importing, we define `BLOCKS_FROM_PIVOT` as the number of blocks between the block number and the `PIVOT_POINT`.

According to these numbers, we can know with 99.9% probability that a preview or import block will not fall outside the `BEAM_WINDOW` if we only choose to import it under the case that.

- `BLOCK_NUMBER - MAX_EXPECTED_IMPORT_TIME_IN_BLOCKS > PIVOT_POINT`
- `BLOCK_NUMBER - MAX_EXPECTED_PREV_TIME_IN_BLOCKS > PIVOT_POINT`

In the case where this condition is not satisfied we should instead choose to pivot our beam sync.

**Comment by carver** [comment]
> I think we could get reasonably reliable results if we define the need to pivot as:
> 
> 1. no forward progress of syncing state after some timeout
>    
>    * all peers fail at returning needed nodes
>    * maybe confirm by checking the actual block state-root node is also not available
> 2. state root of newer blocks is available
>    
>    * at least one peer does return non-empty state requests for "new blocks"

Interestingly, a couple of times, I seem to have connected to some kind of archive node. It will keep feeding me very old state (slowly). So we can't count on 0 results being a reliable trigger. Checking the new state root is interesting, but if we're already stuck behind, seems like we don't lose much by pivoting without checking, which will simplify.

I think we might need to just look at the timestamp diff between the active beam import header and the tip. The downside is that we won't be able to quickly adapt, if the window of trie history shrinks/grows.

Maybe we could expose some kind of command line variable like `--allowed-beam-lag 600` to permit 10 minutes of lag from the tip. Then if other clients change, we could communicate a new flag without requiring a new release.

**Comment by carver** [comment]
> I think we might need to just look at the timestamp diff between the active beam import header and the tip.

Went with block number instead of timestamp. The main reason is that other clients define the window by block number, so if the timestamp gets screwed up (or advances at a different rate, on say a testnet), then the pivot window is still the right size.
