### ISSUE TITLE
Revisit `update_tuple_item`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#911]
### What is wrong?

Per https://github.com/ethereum/py-ssz/pull/84#discussion_r312866552 and https://github.com/ethereum/py-ssz/pull/84/files/48ac9650557ca9591f6403c6146a237bea2b9396#r313158837 discussion.

https://github.com/ethereum/trinity/blob/2644c231f0d7c98128565ba4e5c8cf02e3145f35/eth2/_utils/tuple.py#L49

### How can it be fixed

> @ralexstokes: 
the idea was to ignore any and all positional inputs to this function (and in this case just return some value to do an unconditional swap). i ran into a case where it was helpful to ignore all positional args but it would be worthwhile to revisit our usage of this idiom to see if we still need it.

> a more complete solution is something like `lambda *_, **__: new_value` but we are taking a shortcut in that we don't pass any keyword args here (and expect no one else will either)

**Comment by jannikluhn** [comment]
I don't think the `*_` is necessary at runtime, because we don't pass any `*args` to `update_tuple_item_with_fn`, so the function isn't called with any additional parameters. But since we have a type hint that the function has to fulfill (in Trinity at least, not in py-ssz), we should keep it as it is as far as I can see.

On that note, I think the type hint is wrong: `Callable[[VType, Any], VType]` means that the function takes two arguments, not an arbitrary number. Unfortunately, to my knowledge the only way to fix this would be to use `Callable[..., VType]`, so we'd lose the annotation for the first argument... But since mypy seems to not complain about this right now (which surprises me a little), I think we should just keep it as it is. So I'm closing this, but feel free to reopen if you disagree.

**Comment by ralexstokes** [comment]
these are the only cleanups i see at the moment: https://github.com/ethereum/trinity/compare/master...ralexstokes:fix-use-of-tuple-varargs
