### ISSUE TITLE
Declarative peer/connection driver

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#953]
Related to #454

### What is wrong?

I think that with the upcoming introduction of the [`Connection`](https://github.com/ethereum/trinity/pull/684/files#diff-2c34d249185227655fdb5eee1f50fa59) we will have the necessary abstractions in place to think about declarative testing of protocol stuff.

### How can it be fixed

```python
alice, bob = peer_pair(...)
alice_instructions = alice.compose(
    alice.dial(bob),
    alice.handshake(),
    alice.on(Pong, lambda msg: ...),
    alice.send(Ping())),
)
bob_instructions = bob.compose(
    bob.listen(),
    bob.handshake(),
    bob.on(Ping, alice.send(Pong())),
)
drive_connections(alice_instructions, bob_instructions)
```

The idea here is that we get to completely abstract away the `async` part and write declarative tests that make the concurrency easier to visualize and reason about.

Another nice one is checkpointing.

```python
alice, bob = peer_pair(...)
alice_checkpoint, bob_checkpoint = checkpoint()
alice_instructions = alice.compose(
    alice.dial(bob),
    alice.handshake(),
    alice.on(Pong, lambda msg: ...),
    alice_checkpoint(),  # signals alice ready, waits for bob's signal
    alice.send(Ping())),
)
bob_instructions = bob.compose(
    bob.listen(),
    bob.handshake(),
    bob_checkpoint(),  # signals bob ready, waits for alice's signal.
    bob.on(Ping, alice.send(Pong())),
)
drive_connections(alice_instructions, bob_instructions)
```

In this one, the two checkpoints act as ways to synchronize the two concurrent flows of instructions.

Some other nice benefits.

1. Ability to run them in separate processes (this exposes race conditions that are otherwise never hit due to a singular event loop.
2. Ability to easily define and re-use, and compose behavior sequences.
3. Should force tests towards functionality rather than implementation.
4. Better logging records of exactly what happened during a test run.

**Comment by pipermerriam** [comment]
One thing that looks to be in the way of this is that command instances and message payloads are separate.  Currently, we have no API for generically sending an arbitrary command and message payload.  It can be constructed under the current API but it is a bit awkward to do.

To fix this, I believe some small changes need to be made to the `Protocol` and `Command` constructs.  I think the correct API is going to be merging the command and payload message into a single construct and having a single `Protocol.send_command(cmd_instance)` method.  The `cmd_instance` would contain the full message payload.

The `cmd_id_offset` and `snappy_support` probably move out of the command instance itself, relying on the `Protocol` to keep track of this information (which is already does).  The individual `Command` classes will probably remain responsible for doing the encoding and decoding.

Each `Command` instance would then probably have a `payload` property (maybe a good chance to move away from dictionaries and towards `NamedTuple` for representing command payloads.

**Comment by lithp** [comment]
I'm very down for the proposed changes to `Protocol` and `Command`! Being able to remove the calls to `cast` would be pretty nice, and making a nicer API for writing tests also sounds great. I'm weakly against the full declarative API though.

This structure:

```python
alice_instructions = alice.compose(
    alice.dial(bob),
    alice.handshake(),
    alice.on(Pong, lambda msg: ...),
    alice.send(Ping())),
)
```

isn't very similar to:

```python
async def do_alice():
    await alice.dial(bob)
    await alice.handshake()
    msg = await alice.await_message(Pong)
    await alice.send(Ping(msg))
```

While the second is less declarative, we can easily do arbitrary things inside the second, instead of needing to first extend the DSL / remember how the DSL does the arbitrary thing.

And I think an API which enables the second form could be used in more places than the API which enables the first form. For example, `checkpoint` is something which would only be usable from inside the `compose()` call, but if we wrote an asyncio version of [`threading.Barrier`](https://docs.python.org/3/library/threading.html#barrier-objects) I bet a lot of our other tests would also be happy to use it. I would also love to be able to open bpython and make calls like `alice.dial()` and `alice.await_message()` myself, that sounds great for prototyping!
